<template>
  <div class="text-left">
    <div class="my-8 mx-4 rounded-lg bg-white bg-opacity-70 p-8 py-2">
      <div v-if="lang == 'en'">
        <div class="my-4 font-bold text-white">
          <h2>Privacy Policy</h2>
        </div>
        <div class="my-4">
          At imprompt, we take your privacy seriously. This privacy policy
          explains how we collect, use, store, and share your personal data when
          you use our social networking service
        </div>
        <div class="my-4">
          1. Information we collect We collect the text you enter into our
          service and any text generated by our AI algorithms. We also collect
          per-user information associated with the Twitter ID of the user when
          Twitter is used as the user authentication mechanism. We use Google
          Analytics to monitor the activity of all users, including those who do
          not use our authentication mechanism.
        </div>
        <div class="my-4">
          2. Use of your information All text entered into our service and
          generated by our AI will be publicly accessible and become part of the
          public domain. We reserve the right to remove any content that
          violates our policies, such as hate speech, privacy infringement, or
          copyright violations.
        </div>
        <div class="my-4">
          3. Storage and security of your information We store your personal
          data securely and take appropriate measures to protect it from
          unauthorized access, disclosure, or destruction.
        </div>
        <div class="my-4">
          4. Sharing of your information We do not share your personal data with
          third parties, except in cases where we are required by law to do so.
        </div>
        <div class="my-4">
          5. Changes to our Privacy Policy We may update this privacy policy
          from time to time. We will notify you of any changes by posting the
          new privacy policy on our website.
        </div>
        <div class="my-4">
          By using our social networking service, you agree to the terms of our
          privacy policy.
        </div>
      </div>
      <div v-else>
        <div class="my-4 font-bold text-white">
          <h2>プライバシーポリシー</h2>
        </div>
        <div class="my-4">
          impromptでは、お客様のプライバシーを重視しています。このプライバシーポリシーは、当社のソーシャルネットワーキングサービスを使用する際に、お客様の個人データを収集、利用、保存、共有する方法について説明します。
        </div>
        <div class="my-4">
          1. 収集する情報
          当社は、お客様が入力するテキストおよび当社のAIアルゴリズムで生成されたテキストを収集します。また、Twitterをユーザー認証メカニズムとして使用している場合には、ユーザーのTwitter
          IDに関連するユーザーごとの情報を収集します。また、Google
          Analyticsを使用して、ユーザー認証メカニズムを使用しないすべてのユーザーのアクティビティを監視しています。
        </div>
        <div class="my-4">
          2. 情報の利用
          当社のサービスに入力されたテキストおよび当社のAIによって生成されたテキストは、すべて公開され、パブリックドメインの一部となります。当社は、ヘイトスピーチ、プライバシー侵害、著作権侵害など、当社のポリシーに違反するコンテンツを削除する権利を留保します。
        </div>
        <div class="my-4">
          3. 情報の保存とセキュリティ
          当社は、お客様の個人データを安全に保存し、不正なアクセス、開示、破壊から保護するために適切な措置を講じています。
        </div>
        <div class="my-4">
          4. 情報の共有
          当社は、法律によって要求された場合を除き、お客様の個人データを第三者と共有しません。
        </div>
        <div class="my-4">
          5. プライバシーポリシーの変更
          当社は、このプライバシーポリシーを定期的に更新することがあります。新しいプライバシーポリシーを当社のウェブサイトに掲載することで、変更を通知します。
          本プライバシーポリシーに関するご質問やご不明な点がございましたら、@_impromptまでお問い合わせください。
        </div>
        <div class="my-4">
          当社のソーシャルネットワーキングサービスを使用することにより、本プライバシーポリシーの条件に同意することになります。
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useLang } from "@/i18n/utils";

export default defineComponent({
  setup() {
    const { lang } = useLang();
    return {
      lang,
    };
  },
});
</script>
